/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_myapplication_RendererJNI */

#ifndef _Included_com_example_myapplication_RendererJNI
#define _Included_com_example_myapplication_RendererJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_myapplication_RendererJNI
 * Method:    glesInit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_myapplication_RendererJNI_glesInit
  (JNIEnv *, jobject);

/*
 * Class:     com_example_myapplication_RendererJNI
 * Method:    glesRender
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_myapplication_RendererJNI_glesRender
  (JNIEnv *, jobject);

/*
 * Class:     com_example_myapplication_RendererJNI
 * Method:    glesResize
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_example_myapplication_RendererJNI_glesResize
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
